site:
  title: "Hilscher Demo-Portal"
  url: https://github.io
content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://gitlab.com
output:
  dir: ./public
